### ISSUE TITLE
Wireless range extender

### ISSUE THREAD

**Issue by petakii** [elytra/Correlated#27]
I think that the wireless transmitters range is OK, but if you try to use your wireless terminal far away your main storage, e.g. in your mine, you would need two wireless terminals, one bound to the "upper" transmitter and one for the mine. The solution written on the wiki (controller+receiver+transmitter) didn't work for me, because I the wireless terminal can only be bound to one transmitter.

A solution could be a new block, the range extender, which does nothing but copies the id of the transmitter whose range you want to extend for another 64 blocks or something. This would also need a controller and power source, but would make reaching your storage easier. 

Another solution could be that when your system only consist a controller+receiver+transmitter, it works as an extender and shares the same id as what it's extending, until you connect an interface or a drive bay. After that it becomes a different station.

**Comment by unascribed** [comment]
That's a good point, didn't really think about the binding issue, as I was mainly testing linking networks together.

**Comment by SWederell** [comment]
What about having the wireless range as a config option. I'm looking around for AE alternatives for a 1.10 map I'm creating but I know the player is going to be around 1000 blocks from the main hub network (it'll be in spawn chunks) and having to have random chunks loaded in between for range extenders would be a hassle.

**Comment by unascribed** [comment]
It already is a config option, actually.

I won't be increasing the default, as the current wireless system is simply a stopgap anyway. I want to add large-scale wireless with things like cell towers.

**Comment by SWederell** [comment]
Fair enough. I just took the meaning to be that it was fixed. Sorry for the misunderstanding

**Comment by unascribed** [comment]
I had an idea to use Chorus Fruit to create range extenders that you place in a circle around the current radius. The first level would require 8, and the amount would increase as it got larger.

(This was inspired by a thread I saw on /r/ftb about mods using Chorus Fruit for things, and it makes sense to me because Chorus Fruit teleports you to a random area nearby. It also gates extremely large wireless behind going to an End Island.)

**Comment by unascribed** [comment]
Obsoleted by the new wireless system in 2.0.0a4.
