### ISSUE TITLE
Use player-specific ghost slots for the Terminal crafting grid

### ISSUE THREAD

**Issue by Ghezra** [elytra/Correlated#39]
Currently the items just drop to the floor.

Would like them to go back into the system if possible, or into player inventory if possible, then floor if neither is possible (as an ideal solution)

Or just remain in the crafting grid, although this would mean that the crafting grid would have to be independent of player like the Tinker's Construct crafting grid so you'd have to fight with people over use. So I'd like to not do that particular fix if possible.

**Comment by unascribed** [comment]
There's no reason it can't use the preferences system and be player-dependent.

I could also make them be ghost slots, so that it doesn't use items until you actually craft something. That'd make it a lot more reasonable to store in the preferences per-user.

**Comment by unascribed** [comment]
Hm! I could also make the ghost slots highlight red if there's none in the network or your inventory. This would also fix #42.
