### ISSUE TITLE
@, #, $, %, | searching to fully sync with JEI searching

### ISSUE THREAD

**Issue by Ghezra** [elytra/Correlated#40]
Currently not supported at all as it tries to parse the name of the items for the '@' and '#' character.

Search by Mod Only: Type @ in front of a word
Search by Tooltip Only: Type # in front of a word
Search by OreDict name: Type $ in front of a word
Search by Creative Tab: Type % in front of a word
Multiple Searches: Separate terms with | characters, like "wrench|hammer"

**Comment by unascribed** [comment]
I did notice this, and the best solution is probably to defer to JEI's search engine if it's installed, even if JEI sync is disabled. I'll look into this when I have time.

**Comment by unascribed** [comment]
Fixing this is blocked on #22.

**Comment by unascribed** [comment]
#22 has been closed, and I looked into this; we can't easily leverage JEI's search as it's not intended for use on arbitrary lists of items, only a list of every item in the game. I'll reimplement the important parts in the revamped search.

**Comment by unascribed** [comment]
![image](https://user-images.githubusercontent.com/6185037/30372739-bfe05ab4-984c-11e7-8b87-9dfc671f4859.png)
Implemented.
