### ISSUE TITLE
Clear search on GUI exit

### ISSUE THREAD

**Issue by Ghezra** [elytra/Correlated#41]
Not having the previous search be saved with each opening of the gui. 

Or at least a 'clear search' x to the right of it or a toggle to turn search saving on and off.

**Comment by unascribed** [comment]
You can right-click the search bar to clear it instantly.

**Comment by Ghezra** [comment]
TIL.
That's so useful for now. lol

**Comment by unascribed** [comment]
JEI has the same feature. :P

**Comment by MauveCloud** [comment]
One possibly-unintended side effect I've noticed with this: right-clicking the Terminal's search bar also clears JEI's search bar, even if JEI syncing is deactivated.

**Comment by unascribed** [comment]
That has been fixed in master, and is pending release.

**Comment by unascribed** [comment]
Decided against this, as right-clicking the search bar is good enough. May consider making the terminal not save searches at all, but for now this behavior is staying.
