### ISSUE TITLE
Confusing terminal error message when more memory is needed

### ISSUE THREAD

**Issue by MauveCloud** [elytra/Correlated#47]
When trying to put multiple types of Forestry saplings into CoPo storage, I got the following error message:

> Add: Insufficient disk space.  
> Need about 4039, only 47694 available

Adding more memory helped without needing to increase disk space (I originally only had 1 KiB memory installed, but once I increased it to 5 KiB I was able to put more saplings in), plus the amount of disk space reported available was more than it claimed it needed, making this doubly confusing.

Note: to help clarify why Forestry saplings need so much CoPo memory, here is the output of `/mt hand` (using CraftTweaker) on a Forestry Mundane Larch Sapling:

`<forestry:sapling>.withTag({IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "forestry.treeLarch", UID0: "forestry.treeLarch", Slot: 0 as byte}, {UID1: "forestry.growthLightlevel", UID0: "forestry.growthLightlevel", Slot: 1 as byte}, {UID1: "forestry.heightAverage", UID0: "forestry.heightAverage", Slot: 2 as byte}, {UID1: "forestry.saplingsLow", UID0: "forestry.saplingsLow", Slot: 3 as byte}, {UID1: "forestry.fruitNone", UID0: "forestry.fruitNone", Slot: 4 as byte}, {UID1: "forestry.yieldLowest", UID0: "forestry.yieldLowest", Slot: 5 as byte}, {UID1: "forestry.plantTypeNone", UID0: "forestry.plantTypeNone", Slot: 6 as byte}, {UID1: "forestry.sappinessLower", UID0: "forestry.sappinessLower", Slot: 7 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 8 as byte}, {UID1: "forestry.leavesNone", UID0: "forestry.leavesNone", Slot: 9 as byte}, {UID1: "forestry.maturationAverage", UID0: "forestry.maturationAverage", Slot: 10 as byte}, {UID1: "forestry.i1d", UID0: "forestry.i1d", Slot: 11 as byte}, {UID1: "forestry.i20d", UID0: "forestry.i20d", Slot: 12 as byte}, {UID1: "forestry.i4d", UID0: "forestry.i4d", Slot: 13 as byte}, {UID1: "forestry.fireproofFalse", UID0: "forestry.fireproofFalse", Slot: 14 as byte}]}})`

**Comment by unascribed** [comment]
Yeah, the messages need to be updated to account for memory.

**Comment by unascribed** [comment]
Examples of the new messages:

![image](https://cloud.githubusercontent.com/assets/6185037/23340075/02300266-fbfe-11e6-99d5-e04d80c327ca.png)
![image](https://cloud.githubusercontent.com/assets/6185037/23340099/a9765cf0-fbfe-11e6-8721-2d695ce388b1.png)
![image](https://cloud.githubusercontent.com/assets/6185037/23340104/b05c8080-fbfe-11e6-9cb6-f7ffe80d9372.png)
![image](https://cloud.githubusercontent.com/assets/6185037/23340109/b8f43c4c-fbfe-11e6-9361-2c928f924361.png)
