### ISSUE TITLE
Add EU support

### ISSUE THREAD

**Issue by MauveCloud** [elytra/Correlated#49]
AE2 had an Energy Acceptor (http://ae-mod.info/Energy-Acceptor/) for converting different types of energy into a form that AE2 could use, so why not something similar for CoPo?  afaik, RotaryCraft hasn't been updated past 1.7.10, but IndustrialCraft 2 (https://minecraft.curseforge.com/projects/industrial-craft) and Mekanism (http://aidancbrady.com/mekanism/download/) have 1.10.2 versions, and there's also Tesla that some users might be interested in, which is only for MC 1.9+ (personally, I'm most interested in support for IC2).

Note: it wasn't documented, and might not have been intentional, but AE2's ME Controller could connect to IC2 cables directly and accept power that way without needing the separate Energy Acceptor in between.  IDK whether the controller accepted the other power types that way.

**Comment by unascribed** [comment]
EU support is planned, but the Controller can already accept RF, Tesla, and Forge Energy.

**Comment by MauveCloud** [comment]
I knew RF was supported, since the CurseForge page explicitly mentions it (although I'm not sure the two mods mentioned for providing RF power are such good choices given the amount of RF that CoPo needs by default, and one of them hasn't updated to 1.10.2 yet), but I didn't know Tesla was already added (I thought RF was the only choice, and I'd have to use a generator or converter from another mod to provide it).  Also, I've had trouble finding up-to-date documentation to help me understand what Forge Energy is.

**Comment by unascribed** [comment]
Forge Energy, aka CapabilityEnergy, is a straight port of the RF API to Capabilities, and is part of Forge. For all intents and purposes, it's RF.

The Curse page and wiki still document 1.x, as 2.x isn't done yet. I also wrote that Curse page for 1.8, so I haven't checked it in a while. I'll be rewriting it upon the 2.0.0 release.

**Comment by unascribed** [comment]
Added in 2.0.0a4, though since IC2 isn't available for 1.11.2 yet, it can't really be used.
