### ISSUE TITLE
Wrong error message from terminal when you place the terminal first

### ISSUE THREAD

**Issue by DeGariless** [elytra/Correlated#52]
CoPo 2.0.0
MC 1.10.2

Steps
1. Place a terminal
2. Place a controller adjacent to the terminal
3. Attempt to interact with the terminal

Result: error message "Cannot find a Controller to communicate with."
Expected Result: "The unlit screen resists all attempts at interaction."

It seems like the terminal fails to update when the controller is placed next to it.

**Comment by unascribed** [comment]
This is a side effect of how the Controller works, as it only does its initial scan when it finishes booting.

"Solution": Make the no-power and no-controller messages the same.
