### ISSUE TITLE
Correlated potentialitics registered a dimension type with id -31 before, but doesn't do so in the new version anymore. Note that this is not the usual dimension id, but the dimension type id.

### ISSUE THREAD

**Issue by DietmarKrause** [elytra/Correlated#57]
In the modpack "all the mods" there is an issue with dimension types. It seems correlated potentialistics registered a dimension type with id -31 before, but doesn't do so in the new version anymore. Note that this is not the usual dimension id, but the dimension type id. This leads to old worlds not to be compatible any more.  In the discussion it is stated that Forge needs to fix their dimension type handling to tolerate mod removal/changes which would help in the future to avoid problems like that. But is there any way form the side of CP to help with this issue?
The discussion can be followed here:
fewizz/NotEnoughIDs#55
whatthedrunk/allthemods#447
https://github.com/MinecraftForge/MinecraftForge/issues/3786

Any help would be nice.

**Comment by unascribed** [comment]
Looks like it's fixed now. 👍

I thought this was a Sponge specific issue, the dimension was fine in my
devenv.

If you can't update Forge, just delete the DIM-31 directory.

**Comment by unascribed** [comment]
Oh, nevermind, it looks like All The Mods actually removed Correlated. So this actually has absolutely nothing to do with me and is 100% a Forge bug.

**Comment by DietmarKrause** [comment]
the problem in the mod pack was solved by re-adding correlated, so old worlds are finde after that.
