### ISSUE TITLE
Add the ability to use Embers power to run the system

### ISSUE THREAD

**Issue by Dragnier** [elytra/Correlated#76]
I realize most packs have at least some tech in them and this is a tech themed system. However, to truly differentiate yourself from other tech based storage systems, it would be nice to see you allow the Embers mod power system to work with your system by default without the need for another mod or something.

To be perfectly honest, I've been wishing someone could make a magical themed storage system that would do the same functionality seen in AE2, Refined Storage, and CoPo; but with that would fit better into a nearly completely magic based modpack.

I don't expect such a huge thing from CoPo, but accepting other power than just tech based RF, Tesla, Forge, EU, or Joules would be a decent compromise.

**Comment by asiekierka** [comment]
Why not, instead, write a generic mod which lets you set rates for Forge<->Ember conversion applied to each tile entity separately? It appears Embers's system, like most power systems, is just a single value anyway...

**Comment by unascribed** [comment]
I don't really think there's a reason to do this, it adds another build dependency and the Embers power system isn't good at passive drain as far as I know.
